Added a function to add a td class dynamically
digipolisantwerp/acpaas-ui_angular pull request #208
Opened 2020-08-27 07:47 UTC by dirkg

## PR Checklist

This PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: [Contributing guidelines](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A [changelog entry](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/guidelines/CHANGELOG.md) was added

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

## Resolved issues

2020-09-17 07:51 UTC, dirkg commented
For the sdp project we need to be able to make specific rows of a table in bold.
So I propose to add an extra columClass property to the TableColumn interface.
Thanks for accepting this additional functionality.

2020-09-24 08:55 UTC, MichaelCastiau requested changes

2020-09-24 08:55 UTC, MichaelCastiau commented on packages/ngx-table/src/lib/components/table-cell/table-cell.component.ts
> +  @Input() columnClass: Type<any>;
Dont' use any, please use appropriate typings.

2020-09-24 08:55 UTC, MichaelCastiau commented on packages/ngx-table/src/lib/components/table-cell/table-cell.component.ts
> +  public hasColumnClass() {
There is no need for this method, you can just use `!!this.columnClass` in the template

2020-09-24 08:55 UTC, MichaelCastiau commented on packages/ngx-table/src/lib/services/table-helper.service.ts
> +@Injectable({ providedIn: 'root' })
Please don't use `provideIn`. This will be deprecated in future versions. Dependency inject using declaration in the `NgModule`

2020-09-24 08:55 UTC, MichaelCastiau commented on packages/styleguide/src/examples/pages/aui-table/aui-table.page.ts
> +      columnClass: (value, col, row) => this.makeBold(value, col, row)
Please don't use `this.makeBold` but preferably use functional programming.

2020-09-24 08:55 UTC, MichaelCastiau commented
@dirkg  Additional to comments, please add necessary unit test for the functionality that you've added.

2020-09-30 08:21 UTC, MichaelCastiau commented
@dirkg Please fix your linting for the PR to pass build

2020-10-01 08:17 UTC, MichaelCastiau approved these changes

2020-10-01 08:35 UTC, TriangleJuice approved these changes
Ok for me. Please also add the changes to the CHANGELOG ("Unreleased").

2020-10-02 09:41 UTC, merged