Replaced `BrowserModule` with `CommonModule` in the ngx-navigation-me…
digipolisantwerp/acpaas-ui_angular pull request #212
Opened 2020-09-29 21:01 UTC by jschoubben

ngx-navigation-menu

## PR Checklist

This PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Contributing guidelines](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] A [changelog entry](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/guidelines/CHANGELOG.md) was added

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
It is not possible to use the ngx-navigation-menu component inside a lazy-loaded module because it imports `BrowserModule`

Issue Number: N/A

## What is the new behavior?
It doesn't import `BrowserModule` but instead imports `CommonModule` which it should do following the [Angular Docs](https://angular.io/guide/frequent-ngmodules#browsermodule-and-commonmodule).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

## Resolved issues

2020-09-30 07:25 UTC, TriangleJuice approved these changes

2020-10-02 09:44 UTC, TriangleJuice requested changes

2020-10-02 09:44 UTC, TriangleJuice commented on packages/ngx-navigation-menu/src/lib/navigation-menu.module.ts
> +import {CommonModule} from "@angular/common";
```suggestion
import {CommonModule} from '@angular/common';
```

2020-10-02 09:45 UTC, TriangleJuice approved these changes
I fixed a linting error ;-)

2020-10-02 12:58 UTC, MichaelCastiau approved these changes

2020-10-02 12:58 UTC, merged